function [result] = sync_xcorr(samples_ch, STF_template)

    % determine the lengths of both sequences
    n_samples_ch = numel(samples_ch);
    n_STF_template = numel(STF_template);

    % correlate both sequences
    result = xcorr(samples_ch,STF_template);
    
    % we are only interested in the parts with full overlap, so remove the transient part generated by Matlab
    result = result(n_samples_ch:end-(n_STF_template-1));               
end
